[package]
name = "knock20"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.220", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1", features = ["full"] }
